-- ┌───┐                ┌───┐ --
-- │ ┌─┘ ┌─────┐┌─────┐ └─┐ │ --
-- │ │   │ ┌───┘│ ╶───┤   │ │ --
-- │ │   │ ├───┐└───┐ │   │ │ --
-- │ │   │ └─╴ │┌───┘ │   │ │ --
-- │ └─┐ └─────┘└─────┘ ┌─┘ │ --
-- └───┘                └───┘ --
---@module  "Passenger Pivot Library (Vehicle Only)" <GSCarrier_VehicleOnly>
---@version v0.9.5
---@see     GrandpaScout @ https://github.com/GrandpaScout
-- 

--]] =======================================================================
--]] ⚠ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT EDITING THIS FILE DOES! ⚠
--]]
--]] You have no reason to be modifying this file unless you know how to
--]] modify library files.
--]] (Spoiler alert, *you very likely do not.*)
--]]
--]] If you wish to access the features of this library, use Lua's `require`
--]] system in a different script file to get access to this library's
--]] contents.
--]]
--]]     local Carrier = require("GSCarrier")
--]]
--]] ⚠ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT EDITING THIS FILE DOES! ⚠
--]] =======================================================================

local ID = "GSCarrier_VehicleOnly"
local VER = "0.9.5"
local FIG = {"0.1.2", "0.1.2"}


---===|| LOCALS ||===================================================================================================---

local internal_tags = {
  ["gscarrier:cem"] = true,
  ["gscarrier:player"] = true,
  ["gscarrier:scale"] = true,
  ["pehkui:scale"] = true,
  ["gscarrier:placeholder1"] = true
}


---===|| LIB SETUP ||================================================================================================---

---@class Lib.GS.Carrier
local this = {}

local thismt = {
  __type = ID,
  __metatable = false,
  __index = {
    _ID = ID,
    _VERSION = VER
  }
}


---===|| VEHICLE SETUP ||============================================================================================---

---@type {[integer]: Lib.GS.Carrier.Seat, [string]: integer}
local veh_seats = {}
---@type Lib.GS.Carrier.SeatRemote[]
local veh_remotes = {}
---@type {[Lib.GS.Carrier.vehicleTag]: unknown}
local veh_tags = {["gscarrier:player"] = true}

---@alias Lib.GS.Carrier.seatCallback fun(state: boolean, self: Lib.GS.Carrier.Seat)
---@alias Lib.GS.Carrier.seatCondition fun(ent: Entity.any, tags: {[Lib.GS.Carrier.riderTag]: unknown}, self: Lib.GS.Carrier.Seat): ((boolean | integer)?)

---A seat used to position a rider using the Carrier system.
---@class Lib.GS.Carrier.Seat
---The unique id of this seat.
---
---If seats share priority, the seat with the lower uid will be chosen first.
---@field uid integer
---The name of this seat, this is used with `vehicle.getSeat(name)`.
---@field name string
---The part this seat uses for positioning.
---@field part ModelPart
---The priority of this seat.
---
---Seats with a higher priority will be chosen first.
---@field priority integer
---The tags that define the shape and function of this seat.
---
---These are used by Carrier riders to determine how to act while in this seat.
---@field tags {[Lib.GS.Carrier.seatTag]: unknown}
---The entity currently sitting in this seat.
---@field occupant? Entity.any
---The function to run when a rider using the Carrier system starts or stops sitting in this seat.
---
---The callback is given the state of the seat (`true` for entering, and `false` for leaving) and the seat itself.
---@field callback? Lib.GS.Carrier.seatCallback
---The function to run to check whether a rider using the Carrier system is allowed to use this seat.
---@field condition? Lib.GS.Carrier.seatCondition
local Seat = {}
local SeatMT = {__index = Seat}

---===== METHODS =====---

---Adds a tag to this seat.
---
---If `value` is `nil`, it will default to `true`
---@generic self
---@param self self
---@param tag Lib.GS.Carrier.seatTag
---@param value? any
---@return self
function Seat:addTag(tag, value)
  ---@cast self Lib.GS.Carrier.Seat
  if internal_tags[tag] then error("attempt to modify internal tag '" .. tag .. "'", 2) end
  self.tags[tag] = value == nil or value
  return self
end

---Removes a tag from this seat.
---@generic self
---@param self self
---@param tag Lib.GS.Carrier.seatTag
---@return self
function Seat:removeTag(tag)
  ---@cast self Lib.GS.Carrier.Seat
  if internal_tags[tag] then error("attempt to modify internal tag '" .. tag .. "'", 2) end
  self.tags[tag] = nil
  return self
end


---===== GETTERS =====----

---Gets the name of this seat.
---@return string
function Seat:getName() return self.name end

---Gets the part this seat is using for positioning.
---@return ModelPart
function Seat:getPart() return self.part end

---Gets the priority of this seat.
---@return integer
function Seat:getPriority() return self.priority end

---Gets a copy of the tag list of this seat.
---@return {[Lib.GS.Carrier.seatTag]: unknown}
function Seat:getTags()
  local tbl = {}
  for t, v in pairs(self.tags) do tbl[t] = v end
  return tbl
end

---Gets the entity in this seat.
---@return Entity.any?
function Seat:getOccupant() return self.occupant end

---Gets the callback that will run when a rider using the Carrier system starts or stops sitting in this seat.
---@return Lib.GS.Carrier.seatCallback?
function Seat:getCallback() return self.callback end

---Gets the function that will check whether a rider using the Carrier system is allowed to use this seat.
---@return Lib.GS.Carrier.seatCondition?
function Seat:getCondition() return self.condition end


---===== SETTERS =====---

---Sets the name of this seat.
---@generic self
---@param self self
---@param name string
---@return self
function Seat:setName(name)
  self.name = name
  return self
end

---Gets the part this seat is using for positioning.
---@generic self
---@param self self
---@param part ModelPart
---@return self
function Seat:setPart(part)
  self.part = part
  return self
end

---Sets the priority of this seat.
---@generic self
---@param self self
---@param priority integer
---@return self
function Seat:setPriority(priority)
  self.priority = priority
  return self
end

---Gets the callback that will run when a rider using the Carrier system starts or stops sitting in this seat.
---@param callback? Lib.GS.Carrier.seatCallback
function Seat:setCallback(callback) self.callback = callback end

---Gets the function that will check whether a rider using the Carrier system is allowed to use this seat.
---@param condition? Lib.GS.Carrier.seatCondition
function Seat:getCondition(condition) self.condition = condition end


---@class Lib.GS.Carrier.SeatRemote
---@field uid integer
---@field iterateTags fun(self: Lib.GS.Carrier.SeatRemote): ((fun(uid: integer, name?: Lib.GS.Carrier.seatTag): (Lib.GS.Carrier.seatTag, unknown)), integer)
---@field getPriority fun(self: Lib.GS.Carrier.SeatRemote): integer
---@field getTag fun(self: Lib.GS.Carrier.SeatRemote, name: string): unknown
---@field getOccupant fun(self: Lib.GS.Carrier.SeatRemote): (Entity.any?)
---@field getPos fun(self: Lib.GS.Carrier.SeatRemote): Vector3
---@field getRot fun(self: Lib.GS.Carrier.SeatRemote): Vector3
---@field runCallback fun(self: Lib.GS.Carrier.SeatRemote, state: boolean)
---@field runCondition fun(self: Lib.GS.Carrier.SeatRemote, ent: Entity.any, tags: {[Lib.GS.Carrier.riderTag]: any}): ((boolean | integer)?)
---@field setOccupant fun(self: Lib.GS.Carrier.SeatRemote, ent?: Entity.any)

local function iterate_tags(uid, name) return next(veh_seats[uid].tags, name) end

---@param self Lib.GS.Carrier.SeatRemote
local function remote_iterateTags(self) return iterate_tags, self.uid end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_getPriority(self) return veh_seats[self.uid].priority end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_getTag(self, name) return veh_seats[self.uid].tags[name] end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_getOccupant(self) return veh_seats[self.uid].occupant end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_getPos(self)
  local part = veh_seats[self.uid].part
  return part and part:partToWorldMatrix():apply()
end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_getRot(self)
  local part = veh_seats[self.uid].part
  return part and part:getRot()
end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_runCallback(self, state)
  local seat = veh_seats[self.uid]
  if type(seat.callback) == "function" then pcall(seat.callback, state, seat) end
end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_runCondition(self, ent, tags)
  local seat = veh_seats[self.uid]
  if not seat.part or not seat.part:getVisible() then return false end
  if type(seat.condition) == "function" then
    local s, v = pcall(seat.condition, ent, tags, seat)
    if s then return v end
  end
end
---@param self Lib.GS.Carrier.SeatRemote
local function remote_setOccupant(self, ent) veh_seats[self.uid].occupant = ent end


---===|| VEHICLE TABLE ||============================================================================================---

local vehicle = {}

---===== METHODS =====---

---@class Lib.GS.Carrier.seatOptions
---The priority of this seat.
---
---Seats with a higher priority will be chosen first.
---@field priority? integer
---The tags that define the shape and function of this seat.
---
---These are used by Carrier riders to determine how to act while in this seat.
---@field tags? {[Lib.GS.Carrier.seatTag]: any}
---The function to run when a rider using the Carrier system starts or stops sitting in this seat.
---@field callback? Lib.GS.Carrier.seatCallback
---@field condition? Lib.GS.Carrier.seatCondition

---Creates a new seat at the given part.  
---Use empty groups for best results as they can be freely positioned without moving anything else.
---
---Options may be provided to further customize the seat.
---@param name string
---@param part ModelPart
---@param options? Lib.GS.Carrier.seatOptions
---@return Lib.GS.Carrier.Seat
function vehicle.newSeat(name, part, options)
  if not part then error("given part does not exist", 2) end
  options = options or {}

  ---@type {[Lib.GS.Carrier.seatTag]: unknown}
  local tag_clone = {}
  if options.tags then
    for t, v in pairs(options.tags) do
      if not internal_tags[t] then tag_clone[t] = v end
    end
  end

  local uid = #veh_seats + 1
  local obj = setmetatable({
    uid = uid,
    name = name,
    part = part,
    priority = options.priority or 0,
    tags = tag_clone,
    callback = options.callback,
    condition = options.condition
  }, SeatMT)
  veh_seats[uid] = obj
  veh_seats[name] = uid

  veh_remotes[uid] = {
    uid = uid,
    iterateTags = remote_iterateTags,
    getPriority = remote_getPriority,
    getTag = remote_getTag,
    getOccupant = remote_getOccupant,
    getPos = remote_getPos,
    getRot = remote_getRot,
    runCallback = remote_runCallback,
    runCondition = remote_runCondition,
    setOccupant = remote_setOccupant
  }
  avatar:store("GSCarrier:vehicle.Seats", veh_remotes)

  return obj
end

---Adds a tag to this Carrier vehicle.
---
---If `value` is `nil`, it will default to `true`.
---@param tag Lib.GS.Carrier.vehicleTag
---@param value? any
function vehicle.addTag(tag, value)
  if internal_tags[tag] then error("attempt to modify internal tag '" .. tag .. "'", 2) end
  veh_tags[tag] = value == nil or value
  avatar:store("GSCarrier:vehicle.Tags", veh_tags)
end

---Removes a tag from this Carrier vehicle.
---@param tag Lib.GS.Carrier.vehicleTag
function vehicle.removeTag(tag)
  if internal_tags[tag] then error("attempt to modify internal tag '" .. tag .. "'", 2) end
  veh_tags[tag] = nil
  avatar:store("GSCarrier:vehicle.Tags", veh_tags)
end


---===== GETTERS =====---

---Gets a copy of the tag list of this Carrier vehicle.
---@return {[Lib.GS.Carrier.vehicleTag]: unknown}
function vehicle.getTags()
  local tbl = {}
  for t, v in pairs(veh_tags) do tbl[t] = v end
  return tbl
end

---Gets a table of all Carrier riders on this Carrier vehicle.  
---The keys of this array are the seat UIDs and the values are the entities sitting in those seats.  
---`n` contains the total amount of riders.
---
---Empty seats have a `false` instead of a `nil` to allow `ipairs()` to iterate over this table.
---
---To get the single occupant of a specific seat, use `Seat:getOccupant()`.
---@return {[integer]: Entity.any | false, n: integer}
function vehicle.getOccupants()
  local tbl = {}
  local n = 0
  local occ
  for i, seat in ipairs(veh_seats) do
    occ = seat.occupant or false
    if occ then n = n + 1 end
    tbl[i] = occ
  end

  tbl.n = n
  return tbl
end


---===== SETTERS =====---

---Sets whether this Carrier vehicle will redirect any passengers of the Minecraft vehicle it is controlling to itself.
---
---If a Carrier vehicle controlling a Minecraft boat has redirect enabled, the player in the back seat will instead be
---placed on the Carrier vehicle.
---
---If `state` is `nil`, it will default to `false`.
---@param state? boolean
function vehicle.setRedirect(state) avatar:store("GSCarrier:vehicle.Redirect", not not state) end


avatar:store("GSCarrier:vehicle.Enabled", true)
avatar:store("GSCarrier:vehicle.Redirect", false)
avatar:store("GSCarrier:vehicle.Seats", veh_remotes)
avatar:store("GSCarrier:vehicle.Tags", veh_tags)

this.vehicle = vehicle


---===|| EVENTS ||===================================================================================================---

events.ENTITY_INIT:register(function()
  veh_tags[user:isPlayer() and "gscarrier:player" or "gscarrier:cem"] = true
  avatar:store("GSCarrier:vehicle.Tags", veh_tags)
end)

local mark_for_cleanup = {}

events.TICK:register(function()
  if next(veh_seats) then
    local passengers = player:getPassengers()
    local passenger_set = {}
    local update_seats = false
    if #passengers > 0 then
      for _, ply in ipairs(passengers) do
        passenger_set[ply:getUUID()] = ply:getVariable("GSCarrier:rider.Seat") or false
      end
    end
    local occupant
    for name, seat in ipairs(veh_seats) do
      occupant = seat.occupant
      if occupant and passenger_set[occupant:getUUID()] ~= name then
        if mark_for_cleanup[name] then
          if seat.callback then seat.callback(false, seat) end
          seat.occupant = nil
          update_seats = true
          mark_for_cleanup[name] = nil
        elseif mark_for_cleanup[name] then
          mark_for_cleanup[name] = nil
        else
          mark_for_cleanup[name] = true
        end
      end
    end
    if update_seats then avatar:store("GSCarrier:vehicle.Seats", veh_remotes) end
  end
end, "GSCarrier:Tick_VehiclePassengerCheck")


do return setmetatable(this, thismt) end


---@diagnostic disable: duplicate-doc-alias

---@alias Lib.GS.Carrier.vehicleTag string
---@alias Lib.GS.Carrier.seatTag string
---@alias Lib.GS.Carrier.riderTag string
