---@meta _
---@version 1.0.0

error(
  "This file should not exist in your Figura avatar!\n" +
  "This file's name should start with a §f.§r to hide it from Figura.\n" +
  "The default name for this file is §f.GSCarrier_tags.lua§r",
  2
)

---@diagnostic disable: duplicate-doc-alias


---===|| VEHICLE TAGS ||=============================================================================================---

---Tags that explain the function, shape, and details of a Carrier vehicle.  
---These can be used by riders to determine which animation to play, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the riders, but should be avoided.
---@alias Lib.GS.Carrier.vehicleTag string
---**[CLASS]** *(Internal)*
---***
---This is a non-player entity.
---
---This tag is always applied to non-player entities.
---
---&nbsp;  
---*Conflicts with:*
---> `class:player`
---| "class:cem"
---**[CLASS]** *(Internal)*
---***
---This is a player entity.
---
---This tag is always applied to player entities.
---
---&nbsp;  
---*Conflicts with:*
---> `class:cem`
---| "class:player"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:vertical_posture"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:horizontal_posture"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:bipedal"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:quadrupedal"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:amorphous"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:humanoid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:anthro"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:feral"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:taur"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:amphibian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:frog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:salamander"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:arthropod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:arachnid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:scorpion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:spider"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crustacean"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crab"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lobster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:shrimp"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:insect"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:beetle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ant"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bee"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wasp"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:butterfly"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:moth"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:avian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bird"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hawk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:eagle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:vulture"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goose"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:swan"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:duck"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dove"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pigeon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:corvid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:raven"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jay"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:corvid_magpie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:falcon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:finch"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flamingo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chicken"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:peafowl"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:turkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crane"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:swallow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hummingbird"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:seagull"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:owl"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:parrot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cockatoo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:parakeet"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:heron"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pelican"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:penguin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:woodpecker"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ostrich"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:robin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:stork"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:toucan"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:phoenix"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gryphon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:harpy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:avali"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chocobo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mammal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:antelope"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gazelle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bovine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:buffalo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bison"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:canine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:coyote"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fox"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jackal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:anubian_jackal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tanuki"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wolf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cerberus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:camelid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:alpaca"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:camel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:llama"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:caprine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sheep"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cervine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:deer"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:moose"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:reindeer"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:equine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:donkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:horse"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zebra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pegasus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:unicorn"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:winged_unicorn"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:feline"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cougar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lynx"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ocelot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cheetah"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pantherine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jaguar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:leopard"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tiger"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lagomorph"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hare"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rabbit"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jackalope"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cetacean"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dolphin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:whale"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pinniped"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sea_lion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:seal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:walrus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:marsupial"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:kangaroo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:koala"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:opossum"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:echidna"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:platypus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mustelid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:badger"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ferret"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:otter"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:weasel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:primate"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ape"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gorilla"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:monkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rodent"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:beaver"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chipmunk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hamster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mouse"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:porcupine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:squirrel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:porcine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pig"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:boar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:warthog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ursid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:panda"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bear"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:armadillo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elephant"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:giraffe"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hedgehog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hippopotamus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:human"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hyena"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:raccoon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:red_panda"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rhinoceros"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:skunk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gastropod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:slug"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snail"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cephalopod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:octopus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:octoling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:squid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:inkling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fish"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pufferfish"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:shark"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:reptile"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:alligator"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crocodile"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dinosaur"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lizard"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chameleon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gecko"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:iguana"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snake"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:boa"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cobra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:python"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:viper"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:turtle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tortoise"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:angel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:creeper"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:eastern_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ender_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:western_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:monster_hunter_monster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bird_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:brute_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elder_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fanged_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flying_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:piscine_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fanged_beast"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snake_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lynian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:felyne"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:palico"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gajalaka"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:grimalkyne"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:palamute"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dwarf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:enderman"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fairy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flora_fauna"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dryad"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gnome"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goblin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gorgon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:halfling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hydra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lamia"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:magma_cube"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:manticore"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:yoshi"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:naga"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:orc"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pixie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pokemon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_i"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_ii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_iii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_iv"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_v"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_vi"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_vii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_viii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_ix"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rexouium"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:satyr"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sculk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:warden"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:slime"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sphinx"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:spirit"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ghost"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tiefling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:undead"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:skeleton"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:stray"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wither_skeleton"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mummy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wither"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zombie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:drowned"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:husk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zombified_piglin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:xenomorph"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:yeti"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:machine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:robot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:object"
---**[OBJECT]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "object:pokeball"
---**[TERRAIN]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "terrain:land"
---**[TERRAIN]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "terrain:water"
---**[TERRAIN]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "terrain:underwater"
---**[TERRAIN]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "terrain:air"


---===|| SEAT TAGS ||================================================================================================---

---Tags that explain the function, shape, and details of a seat on a Carrier vehicle.  
---These can be used by riders to determine which animation to play, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the riders, but should be avoided.
---@alias Lib.GS.Carrier.seatTag string
---**[POSITION]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "position:high"
---**[POSITION]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "position:low"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:flat"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:chair"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:mounted"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:piggyback"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:hanging"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:floating"


---===|| RIDER TAGS ||===============================================================================================---

---Tags that explain the function, shape, and details of a Carrier rider.  
---These can be used by vehicles to determine which seat you are allowed to sit in, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the vehicles, but should be avoided.
---@alias Lib.GS.Carrier.riderTag string
---**[CLASS]** *(Internal)*
---***
---This is a non-player entity.
---
---This tag is always applied to non-player entities.
---
---&nbsp;  
---*Conflicts with:*
---> `class:player`
---| "class:cem"
---**[CLASS]** *(Internal)*
---***
---This is a player entity.
---
---This tag is always applied to player entities.
---
---&nbsp;  
---*Conflicts with:*
---> `class:cem`
---| "class:player"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:vertical_posture"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:horizontal_posture"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:bipedal"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:quadrupedal"
---**[SHAPE]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "shape:amorphous"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:humanoid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:anthro"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:feral"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:taur"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:amphibian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:frog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:salamander"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:arthropod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:arachnid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:scorpion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:spider"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crustacean"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crab"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lobster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:shrimp"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:insect"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:beetle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ant"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bee"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wasp"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:butterfly"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:moth"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:avian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bird"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hawk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:eagle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:vulture"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goose"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:swan"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:duck"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dove"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pigeon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:corvid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:raven"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jay"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:corvid_magpie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:falcon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:finch"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flamingo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chicken"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:peafowl"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:turkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crane"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:swallow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hummingbird"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:seagull"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:owl"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:parrot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cockatoo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:parakeet"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:heron"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pelican"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:penguin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:woodpecker"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ostrich"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:robin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:stork"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:toucan"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:phoenix"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gryphon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:harpy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:avali"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chocobo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mammal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:antelope"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gazelle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bovine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:buffalo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bison"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cow"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:canine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:coyote"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fox"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jackal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:anubian_jackal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tanuki"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wolf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cerberus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:camelid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:alpaca"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:camel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:llama"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:caprine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sheep"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cervine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:deer"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:moose"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:reindeer"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:equine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:donkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:horse"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zebra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pegasus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:unicorn"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:winged_unicorn"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:feline"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cougar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lynx"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ocelot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cheetah"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pantherine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jaguar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:leopard"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tiger"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lagomorph"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hare"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rabbit"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:jackalope"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cetacean"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dolphin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:whale"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pinniped"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sea_lion"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:seal"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:walrus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:marsupial"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:kangaroo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:koala"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:opossum"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:echidna"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:platypus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mustelid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:badger"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ferret"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:otter"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:weasel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:primate"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ape"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gorilla"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:monkey"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rodent"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:beaver"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chipmunk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hamster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mouse"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:porcupine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:squirrel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:porcine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pig"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:boar"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:warthog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ursid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:panda"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bear"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:armadillo"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bat"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elephant"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:giraffe"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hedgehog"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hippopotamus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:human"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hyena"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:raccoon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:red_panda"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rhinoceros"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:skunk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gastropod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:slug"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snail"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cephalopod"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:octopus"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:octoling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:squid"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:inkling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fish"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pufferfish"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:shark"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:reptile"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:alligator"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:crocodile"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dinosaur"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lizard"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:chameleon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gecko"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:iguana"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snake"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:boa"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:cobra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:python"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:viper"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:turtle"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tortoise"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:angel"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:creeper"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:eastern_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ender_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:western_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:monster_hunter_monster"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:bird_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:brute_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elder_dragon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fanged_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flying_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:piscine_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fanged_beast"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:snake_wyvern"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lynian"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:felyne"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:palico"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gajalaka"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:grimalkyne"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:palamute"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dwarf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:elf"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:enderman"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:fairy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:flora_fauna"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:dryad"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gnome"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:goblin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gorgon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:halfling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:hydra"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:lamia"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:magma_cube"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:manticore"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:yoshi"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:naga"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:orc"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pixie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:pokemon"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_i"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_ii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_iii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_iv"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_v"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_vi"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_vii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_viii"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:gen_ix"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:rexouium"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:satyr"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sculk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:warden"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:slime"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:sphinx"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:spirit"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:ghost"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:tiefling"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:undead"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:skeleton"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:stray"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wither_skeleton"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:mummy"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:wither"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zombie"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:drowned"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:husk"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:zombified_piglin"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:xenomorph"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:yeti"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:machine"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:robot"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:object"
---**[OBJECT]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "object:pokeball"
