---@meta _
---@version 1.0.0

error(
  "This file should not exist in your Figura avatar!\n" +
  "This file's name should start with a §f.§r to hide it from Figura.\n" +
  "The default name for this file is §f.GSCarrier_tags.lua§r",
  2
)

---@diagnostic disable: duplicate-doc-alias


---===|| VEHICLE TAGS ||=============================================================================================---

---Tags that explain the function, shape, and details of a Carrier vehicle.  
---These can be used by riders to determine which animation to play, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the riders, but should be avoided.
---@alias Lib.GS.Carrier.vehicleTag string
---**[CLASS]** *(Internal)*
---***
---This avatar is a non-player entity.
---
---This tag is always applied to non-player avatars.
---
---&nbsp;  
---*Conflicts with:*
---> `class:player`
---| "class:cem"
---**[CLASS]** *(Internal)*
---***
---This avatar is a player entity.
---
---This tag is always applied to player avatars.
---
---&nbsp;  
---*Conflicts with:*
---> `class:cem`
---| "class:player"
---**[SHAPE]**
---***
---This avatar defaults to a vertical posture.  
---This is mostly orthogrades.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:amorphous`
---| "shape:vertical_posture"
---**[SHAPE]**
---***
---This avatar defaults to a horizontal posture.  
---This is mostly pronogrades.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:vertical_posture`
---| "shape:horizontal_posture"
---**[SHAPE]**
---***
---This avatar has a simple shape.  
---This is common with avatars that are objects/robotic.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:vertical_posture` `shape:amorphous`
---| "shape:simple"
---**[SHAPE]**
---***
---This avatar has no definable shape.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:vertical_posture` `shape:simple`
---| "shape:amorphous"
---**[SPECIES]**
---***
---This avatar has very human-like features.
---
---This can be combined with other species tags to create a (species)-humanoid.
---
---&nbsp;  
---*Conflicts with:*
---> `species:anthro` `species:feral`
---| "species:humanoid"
---**[SPECIES]**
---***
---This avatar has features of an anthropomorphic animal character.
---
---This can be combined with other species tags to create an anthro (species).
---
---&nbsp;  
---*Conflicts with:*
---> `species:humanoid` `species:feral`
---| "species:anthro"
---**[SPECIES]**
---***
---This avatar has features of a feral animal.
---
---This can be combined with other species tags to create a feral (species).
---
---&nbsp;  
---*Conflicts with:*
---> `species:humanoid` `species:anthro`
---| "species:feral"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:taur"
---**[SPECIES]**
---***
---This avatar is an amphibian or has features of one.
---| "species:amphibian"
---**[SPECIES]**
---***
---This avatar is a frog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:amphibian`
---| "species:frog"
---**[SPECIES]**
---***
---This avatar is a salamander or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:amphibian`
---| "species:salamander"
---**[SPECIES]**
---***
---This avatar is an arthropod or has features of one.
---| "species:arthropod"
---**[SPECIES]**
---***
---This avatar is an arachnid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:arachnid"
---**[SPECIES]**
---***
---This avatar is a scorpion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:arachnid`
---| "species:scorpion"
---**[SPECIES]**
---***
---This avatar is a spider or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:arachnid`
---| "species:spider"
---**[SPECIES]**
---***
---This avatar is a crustacean or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:crustacean"
---**[SPECIES]**
---***
---This avatar is a crab or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:crab"
---**[SPECIES]**
---***
---This avatar is a lobster or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:lobster"
---**[SPECIES]**
---***
---This avatar is a shrimp or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:shrimp"
---**[SPECIES]**
---***
---This avatar is an insect or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:insect"
---**[SPECIES]**
---***
---This avatar is a beetle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:beetle"
---**[SPECIES]**
---***
---This avatar is an ant or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:ant"
---**[SPECIES]**
---***
---This avatar is a bee or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:bee"
---**[SPECIES]**
---***
---This avatar is a wasp or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:wasp"
---**[SPECIES]**
---***
---This avatar is a butterfly or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:butterfly"
---**[SPECIES]**
---***
---This avatar is a moth or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:moth"
---**[SPECIES]**
---***
---This avatar is an avian or has features of one.
---| "species:avian"
---**[SPECIES]**
---***
---This avatar is a bird or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:bird"
---**[SPECIES]**
---***
---This avatar is a hawk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:hawk"
---**[SPECIES]**
---***
---This avatar is an eagle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:eagle"
---**[SPECIES]**
---***
---This avatar is a vulture or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:vulture"
---**[SPECIES]**
---***
---This avatar is a goose or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:goose"
---**[SPECIES]**
---***
---This avatar is a swan or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:swan"
---**[SPECIES]**
---***
---This avatar is a duck or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:duck"
---**[SPECIES]**
---***
---This avatar is a dove or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:dove"
---**[SPECIES]**
---***
---This avatar is a pigeon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:pigeon"
---**[SPECIES]**
---***
---This avatar is a corvid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:corvid"
---**[SPECIES]**
---***
---This avatar is a crow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:crow"
---**[SPECIES]**
---***
---This avatar is a raven or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:raven"
---**[SPECIES]**
---***
---This avatar is a jay or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:jay"
---**[SPECIES]**
---***
---This avatar is a corvid magpie or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:corvid_magpie"
---**[SPECIES]**
---***
---This avatar is a falcon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:falcon"
---**[SPECIES]**
---***
---This avatar is a finch or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:finch"
---**[SPECIES]**
---***
---This avatar is a flamingo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:flamingo"
---**[SPECIES]**
---***
---This avatar is a chicken or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:chicken"
---**[SPECIES]**
---***
---This avatar is a peafowl or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:peafowl"
---**[SPECIES]**
---***
---This avatar is a turkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:turkey"
---**[SPECIES]**
---***
---This avatar is a crane or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:crane"
---**[SPECIES]**
---***
---This avatar is a swallow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:swallow"
---**[SPECIES]**
---***
---This avatar is a hummingbird or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:hummingbird"
---**[SPECIES]**
---***
---This avatar is a seagull or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:seagull"
---**[SPECIES]**
---***
---This avatar is a owl or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:owl"
---**[SPECIES]**
---***
---This avatar is a parrot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:parrot"
---**[SPECIES]**
---***
---This avatar is a cockatoo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:parrot`
---| "species:cockatoo"
---**[SPECIES]**
---***
---This avatar is a parakeet or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:parrot`
---| "species:parakeet"
---**[SPECIES]**
---***
---This avatar is a heron or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:heron"
---**[SPECIES]**
---***
---This avatar is a pelican or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:pelican"
---**[SPECIES]**
---***
---This avatar is a penguin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:penguin"
---**[SPECIES]**
---***
---This avatar is a woodpecker or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:woodpecker"
---**[SPECIES]**
---***
---This avatar is an ostrich or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:ostrich"
---**[SPECIES]**
---***
---This avatar is a robin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:robin"
---**[SPECIES]**
---***
---This avatar is a stork or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:stork"
---**[SPECIES]**
---***
---This avatar is a toucan or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:toucan"
---**[SPECIES]**
---***
---This avatar is a phoenix or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:phoenix"
---**[SPECIES]**
---***
---This avatar is a gryphon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:gryphon"
---**[SPECIES]**
---***
---This avatar is a harpy or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:harpy"
---**[SPECIES]**
---***
---This avatar is an avali or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:avali"
---**[SPECIES]**
---***
---This avatar is a chocobo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:chocobo"
---**[SPECIES]**
---***
---This avatar is a mammal or has features of one.
---| "species:mammal"
---**[SPECIES]**
---***
---This avatar is an antelope or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:antelope"
---**[SPECIES]**
---***
---This avatar is a gazelle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:antelope`
---| "species:gazelle"
---**[SPECIES]**
---***
---This avatar is a bovine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:bovine"
---**[SPECIES]**
---***
---This avatar is a buffalo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:buffalo"
---**[SPECIES]**
---***
---This avatar is a bison or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:bison"
---**[SPECIES]**
---***
---This avatar is a cow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:cow"
---**[SPECIES]**
---***
---This avatar is a canine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:canine"
---**[SPECIES]**
---***
---This avatar is a coyote or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:coyote"
---**[SPECIES]**
---***
---This avatar is a domestic dog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:dog"
---**[SPECIES]**
---***
---This avatar is a fox or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:fox"
---**[SPECIES]**
---***
---This avatar is a jackal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:jackal"
---**[SPECIES]**
---***
---This avatar is a anubian_jackal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine` `species:jackal`
---| "species:anubian_jackal"
---**[SPECIES]**
---***
---This avatar is a tanuki or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:tanuki"
---**[SPECIES]**
---***
---This avatar is a wolf or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:wolf"
---**[SPECIES]**
---***
---This avatar is cerberus or has features of the character.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:cerberus"
---**[SPECIES]**
---***
---This avatar is a camelid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:camelid"
---**[SPECIES]**
---***
---This avatar is a alpaca or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:alpaca"
---**[SPECIES]**
---***
---This avatar is a camel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:camel"
---**[SPECIES]**
---***
---This avatar is a llama or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:llama"
---**[SPECIES]**
---***
---This avatar is a caprine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:caprine"
---**[SPECIES]**
---***
---This avatar is a goat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:caprine`
---| "species:goat"
---**[SPECIES]**
---***
---This avatar is a sheep or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:caprine`
---| "species:sheep"
---**[SPECIES]**
---***
---This avatar is a cervine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:cervine"
---**[SPECIES]**
---***
---This avatar is a deer or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:deer"
---**[SPECIES]**
---***
---This avatar is an elk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:elk"
---**[SPECIES]**
---***
---This avatar is a moose or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:moose"
---**[SPECIES]**
---***
---This avatar is a reindeer or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:reindeer"
---**[SPECIES]**
---***
---This avatar is an equine or has features of one.
---| "species:equine"
---**[SPECIES]**
---***
---This avatar is a donkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:donkey"
---**[SPECIES]**
---***
---This avatar is a horse or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:horse"
---**[SPECIES]**
---***
---This avatar is a zebra or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:zebra"
---**[SPECIES]**
---***
---This avatar is a pegasus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:pegasus"
---**[SPECIES]**
---***
---This avatar is a unicorn or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:unicorn"
---**[SPECIES]**
---***
---This avatar is a winged unicorn or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:winged_unicorn"
---**[SPECIES]**
---***
---This avatar is a feline or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:feline"
---**[SPECIES]**
---***
---This avatar is a cougar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cougar"
---**[SPECIES]**
---***
---This avatar is a lynx or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:lynx"
---**[SPECIES]**
---***
---This avatar is anw ocelot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:ocelot"
---**[SPECIES]**
---***
---This avatar is a cheetah or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cheetah"
---**[SPECIES]**
---***
---This avatar is a cat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cat"
---**[SPECIES]**
---***
---This avatar is a pantherine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:pantherine"
---**[SPECIES]**
---***
---This avatar is a jaguar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:jaguar"
---**[SPECIES]**
---***
---This avatar is a leopard or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:leopard"
---**[SPECIES]**
---***
---This avatar is a lion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:lion"
---**[SPECIES]**
---***
---This avatar is a tiger or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:tiger"
---**[SPECIES]**
---***
---This avatar is a lagomorph or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:lagomorph"
---**[SPECIES]**
---***
---This avatar is a hare or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:hare"
---**[SPECIES]**
---***
---This avatar is a rabbit or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:rabbit"
---**[SPECIES]**
---***
---This avatar is a jackalope or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:jackalope"
---**[SPECIES]**
---***
---This avatar is a cetacean or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:cetacean"
---**[SPECIES]**
---***
---This avatar is a dolphin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cetacean`
---| "species:dolphin"
---**[SPECIES]**
---***
---This avatar is a whale or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cetacean`
---| "species:whale"
---**[SPECIES]**
---***
---This avatar is a pinniped or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:pinniped"
---**[SPECIES]**
---***
---This avatar is a sea_lion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:sea_lion"
---**[SPECIES]**
---***
---This avatar is a seal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:seal"
---**[SPECIES]**
---***
---This avatar is a walrus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:walrus"
---**[SPECIES]**
---***
---This avatar is a marsupial or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:marsupial"
---**[SPECIES]**
---***
---This avatar is a kangaroo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:kangaroo"
---**[SPECIES]**
---***
---This avatar is a koala or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:koala"
---**[SPECIES]**
---***
---This avatar is an opossum or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:opossum"
---**[SPECIES]**
---***
---This avatar is anw echidna or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:echidna"
---**[SPECIES]**
---***
---This avatar is a platypus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:platypus"
---**[SPECIES]**
---***
---This avatar is a mustelid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:mustelid"
---**[SPECIES]**
---***
---This avatar is a badger or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:badger"
---**[SPECIES]**
---***
---This avatar is a ferret or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:ferret"
---**[SPECIES]**
---***
---This avatar is a otter or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:otter"
---**[SPECIES]**
---***
---This avatar is a weasel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:weasel"
---**[SPECIES]**
---***
---This avatar is a primate or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:primate"
---**[SPECIES]**
---***
---This avatar is a ape or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:ape"
---**[SPECIES]**
---***
---This avatar is a gorilla or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:gorilla"
---**[SPECIES]**
---***
---This avatar is a monkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:monkey"
---**[SPECIES]**
---***
---This avatar is a rodent or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:rodent"
---**[SPECIES]**
---***
---This avatar is a beaver or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:beaver"
---**[SPECIES]**
---***
---This avatar is a chipmunk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:chipmunk"
---**[SPECIES]**
---***
---This avatar is a hamster or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:hamster"
---**[SPECIES]**
---***
---This avatar is a mouse or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:mouse"
---**[SPECIES]**
---***
---This avatar is a porcupine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:porcupine"
---**[SPECIES]**
---***
---This avatar is a rat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:rat"
---**[SPECIES]**
---***
---This avatar is a squirrel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:squirrel"
---**[SPECIES]**
---***
---This avatar is a porcine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:porcine"
---**[SPECIES]**
---***
---This avatar is a pig or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:pig"
---**[SPECIES]**
---***
---This avatar is a boar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:boar"
---**[SPECIES]**
---***
---This avatar is a warthog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:warthog"
---**[SPECIES]**
---***
---This avatar is a ursid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:ursid"
---**[SPECIES]**
---***
---This avatar is a panda or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:ursid`
---| "species:panda"
---**[SPECIES]**
---***
---This avatar is a bear or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:ursid`
---| "species:bear"
---**[SPECIES]**
---***
---This avatar is an armadillo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:armadillo"
---**[SPECIES]**
---***
---This avatar is a bat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:bat"
---**[SPECIES]**
---***
---This avatar is an elephant or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:elephant"
---**[SPECIES]**
---***
---This avatar is a giraffe or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:giraffe"
---**[SPECIES]**
---***
---This avatar is a hedgehog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hedgehog"
---**[SPECIES]**
---***
---This avatar is a hippopotamus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hippopotamus"
---**[SPECIES]**
---***
---This avatar is a human or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:human"
---**[SPECIES]**
---***
---This avatar is a hyena or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hyena"
---**[SPECIES]**
---***
---This avatar is a raccoon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:raccoon"
---**[SPECIES]**
---***
---This avatar is a red_panda or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:red_panda"
---**[SPECIES]**
---***
---This avatar is a rhinoceros or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:rhinoceros"
---**[SPECIES]**
---***
---This avatar is a skunk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:skunk"
---**[SPECIES]**
---***
---This avatar is a gastropod or has features of one.
---| "species:gastropod"
---**[SPECIES]**
---***
---This avatar is a slug or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:gastropod`
---| "species:slug"
---**[SPECIES]**
---***
---This avatar is a snail or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:gastropod`
---| "species:snail"
---**[SPECIES]**
---***
---This avatar is a cephalopod or has features of one.
---| "species:cephalopod"
---**[SPECIES]**
---***
---This avatar is an octopus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod`
---| "species:octopus"
---**[SPECIES]**
---***
---This avatar is an octoling or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod` `species:octopus`
---| "species:octoling"
---**[SPECIES]**
---***
---This avatar is a squid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod`
---| "species:squid"
---**[SPECIES]**
---***
---This avatar is an inkling or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod` `species:squid`
---| "species:inkling"
---**[SPECIES]**
---***
---This avatar is a fish or has features of one.
---| "species:fish"
---**[SPECIES]**
---***
---This avatar is a pufferfish or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:fish`
---| "species:pufferfish"
---**[SPECIES]**
---***
---This avatar is a shark or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:fish`
---| "species:shark"
---**[SPECIES]**
---***
---This avatar is a reptile or has features of one.
---| "species:reptile"
---**[SPECIES]**
---***
---This avatar is an alligator or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:alligator"
---**[SPECIES]**
---***
---This avatar is a crocodile or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:crocodile"
---**[SPECIES]**
---***
---This avatar is a dinosaur or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:dinosaur"
---**[SPECIES]**
---***
---This avatar is a lizard or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:lizard"
---**[SPECIES]**
---***
---This avatar is a chameleon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:chameleon"
---**[SPECIES]**
---***
---This avatar is a gecko or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:gecko"
---**[SPECIES]**
---***
---This avatar is an iguana or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:iguana"
---**[SPECIES]**
---***
---This avatar is a snake or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:snake"
---**[SPECIES]**
---***
---This avatar is a boa or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:boa"
---**[SPECIES]**
---***
---This avatar is a cobra or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:cobra"
---**[SPECIES]**
---***
---This avatar is a python or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:python"
---**[SPECIES]**
---***
---This avatar is a viper or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:viper"
---**[SPECIES]**
---***
---This avatar is a turtle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:turtle"
---**[SPECIES]**
---***
---This avatar is a tortoise or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:tortoise"
---**[SPECIES]**
---***
---This avatar is an angel or has features of one.
---| "species:angel"
---**[SPECIES]**
---***
---This avatar is a creeper or has features of one.
---| "species:creeper"
---**[SPECIES]**
---***
---This avatar is a dragon or has features of one.
---| "species:dragon"
---**[SPECIES]**
---***
---This avatar is a eastern-style dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:eastern_dragon"
---**[SPECIES]**
---***
---This avatar is an ender dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:ender_dragon"
---**[SPECIES]**
---***
---This avatar is a western-style dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:western_dragon"
---**[SPECIES]**
---***
---This avatar is a wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:wyvern"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter wyvern/monster or has features of one.
---| "species:monster_hunter_monster"
---**[SPECIES]**
---***
---This avatar is a bird wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:bird_wyvern"
---**[SPECIES]**
---***
---This avatar is a brute wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:brute_wyvern"
---**[SPECIES]**
---***
---This avatar is an elder dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:elder_dragon"
---**[SPECIES]**
---***
---This avatar is a fanged wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:fanged_wyvern"
---**[SPECIES]**
---***
---This avatar is a flying wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:flying_wyvern"
---**[SPECIES]**
---***
---This avatar is a piscine wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:piscine_wyvern"
---**[SPECIES]**
---***
---This avatar is a fanged beast or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:fanged_beast"
---**[SPECIES]**
---***
---This avatar is a snake wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:snake_wyvern"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter lynian or has features of one.
---| "species:lynian"
---**[SPECIES]**
---***
---This avatar is a felyne or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:felyne"
---**[SPECIES]**
---***
---This avatar is a palico or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian` `species:felyne`
---| "species:palico"
---**[SPECIES]**
---***
---This avatar is a gajalaka or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:gajalaka"
---**[SPECIES]**
---***
---This avatar is a grimalkyne or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:grimalkyne"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter palamute or has features of one.
---| "species:palamute"
---**[SPECIES]**
---***
---This avatar is a dwarf or has features of one.
---| "species:dwarf"
---**[SPECIES]**
---***
---This avatar is an elf or has features of one.
---| "species:elf"
---**[SPECIES]**
---***
---This avatar is an enderman or has features of one.
---| "species:enderman"
---**[SPECIES]**
---***
---This avatar is a fairy or has features of one.
---| "species:fairy"
---**[SPECIES]**
---***
---This avatar is a living plant or has features of one.
---| "species:flora_fauna"
---**[SPECIES]**
---***
---This avatar is a dryad or has features of one.
---| "species:dryad"
---**[SPECIES]**
---***
---This avatar is a gnome or has features of one.
---| "species:gnome"
---**[SPECIES]**
---***
---This avatar is a goblin or has features of one.
---| "species:goblin"
---**[SPECIES]**
---***
---This avatar is a gorgon or has features of one.
---| "species:gorgon"
---**[SPECIES]**
---***
---This avatar is a halfling or has features of one.
---| "species:halfling"
---**[SPECIES]**
---***
---This avatar is a hydra or has features of one.
---| "species:hydra"
---**[SPECIES]**
---***
---This avatar is a lamia or has features of one.
---| "species:lamia"
---**[SPECIES]**
---***
---This avatar is a magma cube or has features of one.
---| "species:magma_cube"
---**[SPECIES]**
---***
---This avatar is a manticore or has features of one.
---| "species:manticore"
---**[SPECIES]**
---***
---This avatar is a yoshi or has features of one.
---| "species:yoshi"
---**[SPECIES]**
---***
---This avatar is a naga or has features of one.
---| "species:naga"
---**[SPECIES]**
---***
---This avatar is a orc or has features of one.
---| "species:orc"
---**[SPECIES]**
---***
---This avatar is a pixie or has features of one.
---| "species:pixie"
---**[SPECIES]**
---***
---This avatar is a pokemon or has features of one.
---| "species:pokemon"
---**[SPECIES]**
---***
---This avatar is a generation I pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_i"
---**[SPECIES]**
---***
---This avatar is a Lapras or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon` `species:gen_i`
---| "species:lapras"
---**[SPECIES]**
---***
---This avatar is a generation II pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_ii"
---**[SPECIES]**
---***
---This avatar is a generation III pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_iii"
---**[SPECIES]**
---***
---This avatar is a generation IV pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_iv"
---**[SPECIES]**
---***
---This avatar is a generation V pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_v"
---**[SPECIES]**
---***
---This avatar is a generation VI pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_vi"
---**[SPECIES]**
---***
---This avatar is a generation VII pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_vii"
---**[SPECIES]**
---***
---This avatar is a generation VIII pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_viii"
---**[SPECIES]**
---***
---This avatar is a generation IX pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_ix"
---**[SPECIES]**
---***
---This avatar is a shiny pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:shiny_pokemon"
---**[SPECIES]**
---***
---This avatar is a rexouium or has features of one.
---| "species:rexouium"
---**[SPECIES]**
---***
---This avatar is a satyr or has features of one.
---| "species:satyr"
---**[SPECIES]**
---***
---This avatar is sculk or has features of one.
---| "species:sculk"
---**[SPECIES]**
---***
---This avatar is a warden or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:sculk`
---| "species:warden"
---**[SPECIES]**
---***
---This avatar is a slime or has features of one.
---| "species:slime"
---**[SPECIES]**
---***
---This avatar is a sphinx or has features of one.
---| "species:sphinx"
---**[SPECIES]**
---***
---This avatar is a spirit or has features of one.
---| "species:spirit"
---**[SPECIES]**
---***
---This avatar is a ghost or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:spirit`
---| "species:ghost"
---**[SPECIES]**
---***
---This avatar is a tiefling or has features of one.
---| "species:tiefling"
---**[SPECIES]**
---***
---This avatar is an undead or has features of one.
---| "species:undead"
---**[SPECIES]**
---***
---This avatar is a skeleton or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:skeleton"
---**[SPECIES]**
---***
---This avatar is a stray or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:skeleton`
---| "species:stray"
---**[SPECIES]**
---***
---This avatar is a wither skeleton or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:skeleton`
---| "species:wither_skeleton"
---**[SPECIES]**
---***
---This avatar is a mummy or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:mummy"
---**[SPECIES]**
---***
---This avatar is a wither or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:wither"
---**[SPECIES]**
---***
---This avatar is a zombie or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:zombie"
---**[SPECIES]**
---***
---This avatar is a drowned or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:drowned"
---**[SPECIES]**
---***
---This avatar is a husk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:husk"
---**[SPECIES]**
---***
---This avatar is a zombified_piglin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:zombified_piglin"
---**[SPECIES]**
---***
---This avatar is a xenomorph or has features of one.
---| "species:xenomorph"
---**[SPECIES]**
---***
---This avatar is a yeti or has features of one.
---| "species:yeti"
---**[SPECIES]**
---***
---This avatar is a machine or has features of one.
---| "species:machine"
---**[SPECIES]**
---***
---This avatar is a robot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:machine`
---| "species:robot"
---**[SPECIES]**
---***
---This avatar is an object.
---| "species:object"
---**[OBJECT]**
---***
---This avatar is a pokeball or is inside a pokeball.
---| "object:pokeball"
---**[TERRAIN]**
---***
---This avatar prefers to live or travel on land.
---| "terrain:land"
---**[TERRAIN]**
---***
---This avatar prefers to live or travel on water.
---| "terrain:water"
---**[TERRAIN]**
---***
---This avatar prefers to live or travel underwater.
---| "terrain:underwater"
---**[TERRAIN]**
---***
---This avatar prefers to live or travel in air.
---| "terrain:air"


---===|| SEAT TAGS ||================================================================================================---

---Tags that explain the function, shape, and details of a seat on a Carrier vehicle.  
---These can be used by riders to determine which animation to play, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the riders, but should be avoided.
---@alias Lib.GS.Carrier.seatTag string
---**[POSITION]**
---***
---This seat is placed very high off the ground.
---
---&nbsp;  
---*Conflicts with:*
---> `position:low`
---| "position:high"
---**[POSITION]**
---***
---This seat is placed very low to the ground.
---
---&nbsp;  
---*Conflicts with:*
---> `position:high`
---| "position:low"
---**[SHAPE]**
---***
---This seat is flat.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:chair` `shape:mounted` `shape:piggyback` `shape:bridal_carry` `shape:hanging` `shape:floating`
---| "shape:flat"
---**[SHAPE]**
---***
---This seat has room for the legs to hang down as if the rider was sitting in a chair
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:mounted` `shape:piggyback` `shape:bridal_carry` `shape:hanging` `shape:floating`
---| "shape:chair"
---**[SHAPE]**
---***
---This seat is mounted on the back of something like a saddle.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:chair` `shape:piggyback` `shape:bridal_carry` `shape:hanging` `shape:floating`
---| "shape:mounted"
---**[SHAPE]**
---***
---This "seat" causes the rider to be carried piggyback-style.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:chair` `shape:mounted` `shape:bridal_carry` `shape:hanging` `shape:floating`
---| "shape:piggyback"
---**[SHAPE]**
---***
---This "seat" causes the rider to be held in a bridal carry.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:chair` `shape:mounted` `shape:piggyback` `shape:hanging` `shape:floating`
---| "shape:bridal_carry"
---**[SHAPE]**
---***
---This "seat" causes the rider to hang off of something.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:chair` `shape:mounted` `shape:piggyback` `shape:bridal_carry` `shape:floating`
---| "shape:hanging"
---**[SHAPE]**
---***
---This "seat" causes the rider to float in the air.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:flat` `shape:chair` `shape:mounted` `shape:piggyback` `shape:bridal_carry` `shape:hanging`
---| "shape:floating"


---===|| RIDER TAGS ||===============================================================================================---

---Tags that explain the function, shape, and details of a Carrier rider.  
---These can be used by vehicles to determine which seat you are allowed to sit in, for example.
---
---You are not limited to the tags in this list and if you want to add a tag of your own,
---use the format `author:tag_name`.
---
---Usage of conflicting tags results in behavior defined by the vehicles, but should be avoided.
---@alias Lib.GS.Carrier.riderTag string
---**[CLASS]** *(Internal)*
---***
---This avatar is a non-player entity.
---
---This tag is always applied to non-player avatars.
---
---&nbsp;  
---*Conflicts with:*
---> `class:player`
---| "class:cem"
---**[CLASS]** *(Internal)*
---***
---This avatar is a player entity.
---
---This tag is always applied to player avatars.
---
---&nbsp;  
---*Conflicts with:*
---> `class:cem`
---| "class:player"
---**[SHAPE]**
---***
---This avatar defaults to a vertical posture.  
---This is mostly orthogrades.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:amorphous`
---| "shape:vertical_posture"
---**[SHAPE]**
---***
---This avatar defaults to a horizontal posture.  
---This is mostly pronogrades.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:vertical_posture`
---| "shape:horizontal_posture"
---**[SHAPE]**
---***
---This avatar has a simple shape.  
---This is common with avatars that are objects/robotic.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:vertical_posture` `shape:amorphous`
---| "shape:simple"
---**[SHAPE]**
---***
---This avatar has no definable shape.
---
---&nbsp;  
---*Conflicts with:*
---> `shape:horizontal_posture` `shape:vertical_posture` `shape:simple`
---| "shape:amorphous"
---**[SPECIES]**
---***
---This avatar has very human-like features.
---
---This can be combined with other species tags to create a (species)-humanoid.
---
---&nbsp;  
---*Conflicts with:*
---> `species:anthro` `species:feral`
---| "species:humanoid"
---**[SPECIES]**
---***
---This avatar has features of an anthropomorphic animal character.
---
---This can be combined with other species tags to create an anthro (species).
---
---&nbsp;  
---*Conflicts with:*
---> `species:humanoid` `species:feral`
---| "species:anthro"
---**[SPECIES]**
---***
---This avatar has features of a feral animal.
---
---This can be combined with other species tags to create a feral (species).
---
---&nbsp;  
---*Conflicts with:*
---> `species:humanoid` `species:anthro`
---| "species:feral"
---**[SPECIES]**
---***
---```yaml
---  !!TAG_DATA_MISSING!!
---```
---| "species:taur"
---**[SPECIES]**
---***
---This avatar is an amphibian or has features of one.
---| "species:amphibian"
---**[SPECIES]**
---***
---This avatar is a frog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:amphibian`
---| "species:frog"
---**[SPECIES]**
---***
---This avatar is a salamander or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:amphibian`
---| "species:salamander"
---**[SPECIES]**
---***
---This avatar is an arthropod or has features of one.
---| "species:arthropod"
---**[SPECIES]**
---***
---This avatar is an arachnid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:arachnid"
---**[SPECIES]**
---***
---This avatar is a scorpion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:arachnid`
---| "species:scorpion"
---**[SPECIES]**
---***
---This avatar is a spider or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:arachnid`
---| "species:spider"
---**[SPECIES]**
---***
---This avatar is a crustacean or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:crustacean"
---**[SPECIES]**
---***
---This avatar is a crab or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:crab"
---**[SPECIES]**
---***
---This avatar is a lobster or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:lobster"
---**[SPECIES]**
---***
---This avatar is a shrimp or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:crustacean`
---| "species:shrimp"
---**[SPECIES]**
---***
---This avatar is an insect or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod`
---| "species:insect"
---**[SPECIES]**
---***
---This avatar is a beetle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:beetle"
---**[SPECIES]**
---***
---This avatar is an ant or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:ant"
---**[SPECIES]**
---***
---This avatar is a bee or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:bee"
---**[SPECIES]**
---***
---This avatar is a wasp or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:wasp"
---**[SPECIES]**
---***
---This avatar is a butterfly or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:butterfly"
---**[SPECIES]**
---***
---This avatar is a moth or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:arthropod` `species:insect`
---| "species:moth"
---**[SPECIES]**
---***
---This avatar is an avian or has features of one.
---| "species:avian"
---**[SPECIES]**
---***
---This avatar is a bird or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:bird"
---**[SPECIES]**
---***
---This avatar is a hawk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:hawk"
---**[SPECIES]**
---***
---This avatar is an eagle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:eagle"
---**[SPECIES]**
---***
---This avatar is a vulture or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:vulture"
---**[SPECIES]**
---***
---This avatar is a goose or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:goose"
---**[SPECIES]**
---***
---This avatar is a swan or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:swan"
---**[SPECIES]**
---***
---This avatar is a duck or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:duck"
---**[SPECIES]**
---***
---This avatar is a dove or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:dove"
---**[SPECIES]**
---***
---This avatar is a pigeon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:pigeon"
---**[SPECIES]**
---***
---This avatar is a corvid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:corvid"
---**[SPECIES]**
---***
---This avatar is a crow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:crow"
---**[SPECIES]**
---***
---This avatar is a raven or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:raven"
---**[SPECIES]**
---***
---This avatar is a jay or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:jay"
---**[SPECIES]**
---***
---This avatar is a corvid magpie or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:corvid`
---| "species:corvid_magpie"
---**[SPECIES]**
---***
---This avatar is a falcon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:falcon"
---**[SPECIES]**
---***
---This avatar is a finch or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:finch"
---**[SPECIES]**
---***
---This avatar is a flamingo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:flamingo"
---**[SPECIES]**
---***
---This avatar is a chicken or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:chicken"
---**[SPECIES]**
---***
---This avatar is a peafowl or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:peafowl"
---**[SPECIES]**
---***
---This avatar is a turkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:turkey"
---**[SPECIES]**
---***
---This avatar is a crane or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:crane"
---**[SPECIES]**
---***
---This avatar is a swallow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:swallow"
---**[SPECIES]**
---***
---This avatar is a hummingbird or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:hummingbird"
---**[SPECIES]**
---***
---This avatar is a seagull or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:seagull"
---**[SPECIES]**
---***
---This avatar is a owl or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:owl"
---**[SPECIES]**
---***
---This avatar is a parrot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:parrot"
---**[SPECIES]**
---***
---This avatar is a cockatoo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:parrot`
---| "species:cockatoo"
---**[SPECIES]**
---***
---This avatar is a parakeet or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird` `species:parrot`
---| "species:parakeet"
---**[SPECIES]**
---***
---This avatar is a heron or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:heron"
---**[SPECIES]**
---***
---This avatar is a pelican or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:pelican"
---**[SPECIES]**
---***
---This avatar is a penguin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:penguin"
---**[SPECIES]**
---***
---This avatar is a woodpecker or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:woodpecker"
---**[SPECIES]**
---***
---This avatar is an ostrich or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:ostrich"
---**[SPECIES]**
---***
---This avatar is a robin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:robin"
---**[SPECIES]**
---***
---This avatar is a stork or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:stork"
---**[SPECIES]**
---***
---This avatar is a toucan or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:toucan"
---**[SPECIES]**
---***
---This avatar is a phoenix or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian` `species:bird`
---| "species:phoenix"
---**[SPECIES]**
---***
---This avatar is a gryphon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:gryphon"
---**[SPECIES]**
---***
---This avatar is a harpy or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:harpy"
---**[SPECIES]**
---***
---This avatar is an avali or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:avali"
---**[SPECIES]**
---***
---This avatar is a chocobo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:avian`
---| "species:chocobo"
---**[SPECIES]**
---***
---This avatar is a mammal or has features of one.
---| "species:mammal"
---**[SPECIES]**
---***
---This avatar is an antelope or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:antelope"
---**[SPECIES]**
---***
---This avatar is a gazelle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:antelope`
---| "species:gazelle"
---**[SPECIES]**
---***
---This avatar is a bovine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:bovine"
---**[SPECIES]**
---***
---This avatar is a buffalo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:buffalo"
---**[SPECIES]**
---***
---This avatar is a bison or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:bison"
---**[SPECIES]**
---***
---This avatar is a cow or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:bovine`
---| "species:cow"
---**[SPECIES]**
---***
---This avatar is a canine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:canine"
---**[SPECIES]**
---***
---This avatar is a coyote or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:coyote"
---**[SPECIES]**
---***
---This avatar is a domestic dog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:dog"
---**[SPECIES]**
---***
---This avatar is a fox or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:fox"
---**[SPECIES]**
---***
---This avatar is a jackal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:jackal"
---**[SPECIES]**
---***
---This avatar is a anubian_jackal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine` `species:jackal`
---| "species:anubian_jackal"
---**[SPECIES]**
---***
---This avatar is a tanuki or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:tanuki"
---**[SPECIES]**
---***
---This avatar is a wolf or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:wolf"
---**[SPECIES]**
---***
---This avatar is cerberus or has features of the character.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:canine`
---| "species:cerberus"
---**[SPECIES]**
---***
---This avatar is a camelid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:camelid"
---**[SPECIES]**
---***
---This avatar is a alpaca or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:alpaca"
---**[SPECIES]**
---***
---This avatar is a camel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:camel"
---**[SPECIES]**
---***
---This avatar is a llama or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:camelid`
---| "species:llama"
---**[SPECIES]**
---***
---This avatar is a caprine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:caprine"
---**[SPECIES]**
---***
---This avatar is a goat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:caprine`
---| "species:goat"
---**[SPECIES]**
---***
---This avatar is a sheep or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:caprine`
---| "species:sheep"
---**[SPECIES]**
---***
---This avatar is a cervine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:cervine"
---**[SPECIES]**
---***
---This avatar is a deer or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:deer"
---**[SPECIES]**
---***
---This avatar is an elk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:elk"
---**[SPECIES]**
---***
---This avatar is a moose or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:moose"
---**[SPECIES]**
---***
---This avatar is a reindeer or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cervine`
---| "species:reindeer"
---**[SPECIES]**
---***
---This avatar is an equine or has features of one.
---| "species:equine"
---**[SPECIES]**
---***
---This avatar is a donkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:donkey"
---**[SPECIES]**
---***
---This avatar is a horse or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:horse"
---**[SPECIES]**
---***
---This avatar is a zebra or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:zebra"
---**[SPECIES]**
---***
---This avatar is a pegasus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:pegasus"
---**[SPECIES]**
---***
---This avatar is a unicorn or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:unicorn"
---**[SPECIES]**
---***
---This avatar is a winged unicorn or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:equine`
---| "species:winged_unicorn"
---**[SPECIES]**
---***
---This avatar is a feline or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:feline"
---**[SPECIES]**
---***
---This avatar is a cougar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cougar"
---**[SPECIES]**
---***
---This avatar is a lynx or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:lynx"
---**[SPECIES]**
---***
---This avatar is anw ocelot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:ocelot"
---**[SPECIES]**
---***
---This avatar is a cheetah or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cheetah"
---**[SPECIES]**
---***
---This avatar is a cat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:feline`
---| "species:cat"
---**[SPECIES]**
---***
---This avatar is a pantherine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:pantherine"
---**[SPECIES]**
---***
---This avatar is a jaguar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:jaguar"
---**[SPECIES]**
---***
---This avatar is a leopard or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:leopard"
---**[SPECIES]**
---***
---This avatar is a lion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:lion"
---**[SPECIES]**
---***
---This avatar is a tiger or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pantherine`
---| "species:tiger"
---**[SPECIES]**
---***
---This avatar is a lagomorph or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:lagomorph"
---**[SPECIES]**
---***
---This avatar is a hare or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:hare"
---**[SPECIES]**
---***
---This avatar is a rabbit or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:rabbit"
---**[SPECIES]**
---***
---This avatar is a jackalope or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:lagomorph`
---| "species:jackalope"
---**[SPECIES]**
---***
---This avatar is a cetacean or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:cetacean"
---**[SPECIES]**
---***
---This avatar is a dolphin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cetacean`
---| "species:dolphin"
---**[SPECIES]**
---***
---This avatar is a whale or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:cetacean`
---| "species:whale"
---**[SPECIES]**
---***
---This avatar is a pinniped or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:pinniped"
---**[SPECIES]**
---***
---This avatar is a sea_lion or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:sea_lion"
---**[SPECIES]**
---***
---This avatar is a seal or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:seal"
---**[SPECIES]**
---***
---This avatar is a walrus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:pinniped`
---| "species:walrus"
---**[SPECIES]**
---***
---This avatar is a marsupial or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:marsupial"
---**[SPECIES]**
---***
---This avatar is a kangaroo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:kangaroo"
---**[SPECIES]**
---***
---This avatar is a koala or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:koala"
---**[SPECIES]**
---***
---This avatar is an opossum or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:marsupial`
---| "species:opossum"
---**[SPECIES]**
---***
---This avatar is anw echidna or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:echidna"
---**[SPECIES]**
---***
---This avatar is a platypus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:platypus"
---**[SPECIES]**
---***
---This avatar is a mustelid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:mustelid"
---**[SPECIES]**
---***
---This avatar is a badger or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:badger"
---**[SPECIES]**
---***
---This avatar is a ferret or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:ferret"
---**[SPECIES]**
---***
---This avatar is a otter or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:otter"
---**[SPECIES]**
---***
---This avatar is a weasel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:mustelid`
---| "species:weasel"
---**[SPECIES]**
---***
---This avatar is a primate or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:primate"
---**[SPECIES]**
---***
---This avatar is a ape or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:ape"
---**[SPECIES]**
---***
---This avatar is a gorilla or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:gorilla"
---**[SPECIES]**
---***
---This avatar is a monkey or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:primate`
---| "species:monkey"
---**[SPECIES]**
---***
---This avatar is a rodent or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:rodent"
---**[SPECIES]**
---***
---This avatar is a beaver or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:beaver"
---**[SPECIES]**
---***
---This avatar is a chipmunk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:chipmunk"
---**[SPECIES]**
---***
---This avatar is a hamster or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:hamster"
---**[SPECIES]**
---***
---This avatar is a mouse or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:mouse"
---**[SPECIES]**
---***
---This avatar is a porcupine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:porcupine"
---**[SPECIES]**
---***
---This avatar is a rat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:rat"
---**[SPECIES]**
---***
---This avatar is a squirrel or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:rodent`
---| "species:squirrel"
---**[SPECIES]**
---***
---This avatar is a porcine or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:porcine"
---**[SPECIES]**
---***
---This avatar is a pig or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:pig"
---**[SPECIES]**
---***
---This avatar is a boar or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:boar"
---**[SPECIES]**
---***
---This avatar is a warthog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:porcine`
---| "species:warthog"
---**[SPECIES]**
---***
---This avatar is a ursid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:ursid"
---**[SPECIES]**
---***
---This avatar is a panda or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:ursid`
---| "species:panda"
---**[SPECIES]**
---***
---This avatar is a bear or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal` `species:ursid`
---| "species:bear"
---**[SPECIES]**
---***
---This avatar is an armadillo or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:armadillo"
---**[SPECIES]**
---***
---This avatar is a bat or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:bat"
---**[SPECIES]**
---***
---This avatar is an elephant or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:elephant"
---**[SPECIES]**
---***
---This avatar is a giraffe or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:giraffe"
---**[SPECIES]**
---***
---This avatar is a hedgehog or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hedgehog"
---**[SPECIES]**
---***
---This avatar is a hippopotamus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hippopotamus"
---**[SPECIES]**
---***
---This avatar is a human or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:human"
---**[SPECIES]**
---***
---This avatar is a hyena or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:hyena"
---**[SPECIES]**
---***
---This avatar is a raccoon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:raccoon"
---**[SPECIES]**
---***
---This avatar is a red_panda or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:red_panda"
---**[SPECIES]**
---***
---This avatar is a rhinoceros or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:rhinoceros"
---**[SPECIES]**
---***
---This avatar is a skunk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:mammal`
---| "species:skunk"
---**[SPECIES]**
---***
---This avatar is a gastropod or has features of one.
---| "species:gastropod"
---**[SPECIES]**
---***
---This avatar is a slug or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:gastropod`
---| "species:slug"
---**[SPECIES]**
---***
---This avatar is a snail or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:gastropod`
---| "species:snail"
---**[SPECIES]**
---***
---This avatar is a cephalopod or has features of one.
---| "species:cephalopod"
---**[SPECIES]**
---***
---This avatar is an octopus or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod`
---| "species:octopus"
---**[SPECIES]**
---***
---This avatar is an octoling or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod` `species:octopus`
---| "species:octoling"
---**[SPECIES]**
---***
---This avatar is a squid or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod`
---| "species:squid"
---**[SPECIES]**
---***
---This avatar is an inkling or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:cephalopod` `species:squid`
---| "species:inkling"
---**[SPECIES]**
---***
---This avatar is a fish or has features of one.
---| "species:fish"
---**[SPECIES]**
---***
---This avatar is a pufferfish or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:fish`
---| "species:pufferfish"
---**[SPECIES]**
---***
---This avatar is a shark or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:fish`
---| "species:shark"
---**[SPECIES]**
---***
---This avatar is a reptile or has features of one.
---| "species:reptile"
---**[SPECIES]**
---***
---This avatar is an alligator or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:alligator"
---**[SPECIES]**
---***
---This avatar is a crocodile or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:crocodile"
---**[SPECIES]**
---***
---This avatar is a dinosaur or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:dinosaur"
---**[SPECIES]**
---***
---This avatar is a lizard or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:lizard"
---**[SPECIES]**
---***
---This avatar is a chameleon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:chameleon"
---**[SPECIES]**
---***
---This avatar is a gecko or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:gecko"
---**[SPECIES]**
---***
---This avatar is an iguana or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:lizard`
---| "species:iguana"
---**[SPECIES]**
---***
---This avatar is a snake or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:snake"
---**[SPECIES]**
---***
---This avatar is a boa or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:boa"
---**[SPECIES]**
---***
---This avatar is a cobra or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:cobra"
---**[SPECIES]**
---***
---This avatar is a python or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:python"
---**[SPECIES]**
---***
---This avatar is a viper or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile` `species:snake`
---| "species:viper"
---**[SPECIES]**
---***
---This avatar is a turtle or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:turtle"
---**[SPECIES]**
---***
---This avatar is a tortoise or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:reptile`
---| "species:tortoise"
---**[SPECIES]**
---***
---This avatar is an angel or has features of one.
---| "species:angel"
---**[SPECIES]**
---***
---This avatar is a creeper or has features of one.
---| "species:creeper"
---**[SPECIES]**
---***
---This avatar is a dragon or has features of one.
---| "species:dragon"
---**[SPECIES]**
---***
---This avatar is a eastern-style dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:eastern_dragon"
---**[SPECIES]**
---***
---This avatar is an ender dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:ender_dragon"
---**[SPECIES]**
---***
---This avatar is a western-style dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:western_dragon"
---**[SPECIES]**
---***
---This avatar is a wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:dragon`
---| "species:wyvern"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter wyvern/monster or has features of one.
---| "species:monster_hunter_monster"
---**[SPECIES]**
---***
---This avatar is a bird wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:bird_wyvern"
---**[SPECIES]**
---***
---This avatar is a brute wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:brute_wyvern"
---**[SPECIES]**
---***
---This avatar is an elder dragon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:elder_dragon"
---**[SPECIES]**
---***
---This avatar is a fanged wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:fanged_wyvern"
---**[SPECIES]**
---***
---This avatar is a flying wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:flying_wyvern"
---**[SPECIES]**
---***
---This avatar is a piscine wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:piscine_wyvern"
---**[SPECIES]**
---***
---This avatar is a fanged beast or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:fanged_beast"
---**[SPECIES]**
---***
---This avatar is a snake wyvern or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:monster_hunter_monster`
---| "species:snake_wyvern"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter lynian or has features of one.
---| "species:lynian"
---**[SPECIES]**
---***
---This avatar is a felyne or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:felyne"
---**[SPECIES]**
---***
---This avatar is a palico or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian` `species:felyne`
---| "species:palico"
---**[SPECIES]**
---***
---This avatar is a gajalaka or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:gajalaka"
---**[SPECIES]**
---***
---This avatar is a grimalkyne or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:lynian`
---| "species:grimalkyne"
---**[SPECIES]**
---***
---This avatar is a Monster Hunter palamute or has features of one.
---| "species:palamute"
---**[SPECIES]**
---***
---This avatar is a dwarf or has features of one.
---| "species:dwarf"
---**[SPECIES]**
---***
---This avatar is an elf or has features of one.
---| "species:elf"
---**[SPECIES]**
---***
---This avatar is an enderman or has features of one.
---| "species:enderman"
---**[SPECIES]**
---***
---This avatar is a fairy or has features of one.
---| "species:fairy"
---**[SPECIES]**
---***
---This avatar is a living plant or has features of one.
---| "species:flora_fauna"
---**[SPECIES]**
---***
---This avatar is a dryad or has features of one.
---| "species:dryad"
---**[SPECIES]**
---***
---This avatar is a gnome or has features of one.
---| "species:gnome"
---**[SPECIES]**
---***
---This avatar is a goblin or has features of one.
---| "species:goblin"
---**[SPECIES]**
---***
---This avatar is a gorgon or has features of one.
---| "species:gorgon"
---**[SPECIES]**
---***
---This avatar is a halfling or has features of one.
---| "species:halfling"
---**[SPECIES]**
---***
---This avatar is a hydra or has features of one.
---| "species:hydra"
---**[SPECIES]**
---***
---This avatar is a lamia or has features of one.
---| "species:lamia"
---**[SPECIES]**
---***
---This avatar is a magma cube or has features of one.
---| "species:magma_cube"
---**[SPECIES]**
---***
---This avatar is a manticore or has features of one.
---| "species:manticore"
---**[SPECIES]**
---***
---This avatar is a yoshi or has features of one.
---| "species:yoshi"
---**[SPECIES]**
---***
---This avatar is a naga or has features of one.
---| "species:naga"
---**[SPECIES]**
---***
---This avatar is a orc or has features of one.
---| "species:orc"
---**[SPECIES]**
---***
---This avatar is a pixie or has features of one.
---| "species:pixie"
---**[SPECIES]**
---***
---This avatar is a pokemon or has features of one.
---| "species:pokemon"
---**[SPECIES]**
---***
---This avatar is a generation I pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_i"
---**[SPECIES]**
---***
---This avatar is a Lapras or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon` `species:gen_i`
---| "species:lapras"
---**[SPECIES]**
---***
---This avatar is a generation II pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_ii"
---**[SPECIES]**
---***
---This avatar is a generation III pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_iii"
---**[SPECIES]**
---***
---This avatar is a generation IV pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_iv"
---**[SPECIES]**
---***
---This avatar is a generation V pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_v"
---**[SPECIES]**
---***
---This avatar is a generation VI pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_vi"
---**[SPECIES]**
---***
---This avatar is a generation VII pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_vii"
---**[SPECIES]**
---***
---This avatar is a generation VIII pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_viii"
---**[SPECIES]**
---***
---This avatar is a generation IX pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:gen_ix"
---**[SPECIES]**
---***
---This avatar is a shiny pokemon or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:pokemon`
---| "species:shiny_pokemon"
---**[SPECIES]**
---***
---This avatar is a rexouium or has features of one.
---| "species:rexouium"
---**[SPECIES]**
---***
---This avatar is a satyr or has features of one.
---| "species:satyr"
---**[SPECIES]**
---***
---This avatar is sculk or has features of one.
---| "species:sculk"
---**[SPECIES]**
---***
---This avatar is a warden or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:sculk`
---| "species:warden"
---**[SPECIES]**
---***
---This avatar is a slime or has features of one.
---| "species:slime"
---**[SPECIES]**
---***
---This avatar is a sphinx or has features of one.
---| "species:sphinx"
---**[SPECIES]**
---***
---This avatar is a spirit or has features of one.
---| "species:spirit"
---**[SPECIES]**
---***
---This avatar is a ghost or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:spirit`
---| "species:ghost"
---**[SPECIES]**
---***
---This avatar is a tiefling or has features of one.
---| "species:tiefling"
---**[SPECIES]**
---***
---This avatar is an undead or has features of one.
---| "species:undead"
---**[SPECIES]**
---***
---This avatar is a skeleton or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:skeleton"
---**[SPECIES]**
---***
---This avatar is a stray or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:skeleton`
---| "species:stray"
---**[SPECIES]**
---***
---This avatar is a wither skeleton or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:skeleton`
---| "species:wither_skeleton"
---**[SPECIES]**
---***
---This avatar is a mummy or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:mummy"
---**[SPECIES]**
---***
---This avatar is a wither or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:wither"
---**[SPECIES]**
---***
---This avatar is a zombie or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead`
---| "species:zombie"
---**[SPECIES]**
---***
---This avatar is a drowned or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:drowned"
---**[SPECIES]**
---***
---This avatar is a husk or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:husk"
---**[SPECIES]**
---***
---This avatar is a zombified_piglin or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:undead` `species:zombie`
---| "species:zombified_piglin"
---**[SPECIES]**
---***
---This avatar is a xenomorph or has features of one.
---| "species:xenomorph"
---**[SPECIES]**
---***
---This avatar is a yeti or has features of one.
---| "species:yeti"
---**[SPECIES]**
---***
---This avatar is a machine or has features of one.
---| "species:machine"
---**[SPECIES]**
---***
---This avatar is a robot or has features of one.
---
---&nbsp;  
---*Implies:*
---> `species:machine`
---| "species:robot"
---**[SPECIES]**
---***
---This avatar is an object.
---| "species:object"
---**[OBJECT]**
---***
---This avatar is a pokeball or is inside a pokeball.
---| "object:pokeball"
